## code to prepare `sw_summary` dataset goes here
require(tibble)
require(datapasta)
# starwars data (groups) ---------------------------------------------------
# starwars <- dplyr::starwars
# sw_summary <- starwars |>
#               dplyr::select(!where(is.list)) |>
#               dplyr::select(name,
#                             ht = height,
#                             mass,
#                             gender,
#                             hair = hair_color,
#                             eyes = eye_color,
#                             home = homeworld,
#                             species)
sw_summary <- tibble::tribble(
                    ~name,  ~ht, ~mass,     ~gender,           ~hair,           ~eyes,            ~home,          ~species,
         "Luke Skywalker", 172L,    77, "masculine",         "blond",          "blue",       "Tatooine",           "Human",
                  "C-3PO", 167L,    75, "masculine",              NA,        "yellow",       "Tatooine",           "Droid",
                  "R2-D2",  96L,    32, "masculine",              NA,           "red",          "Naboo",           "Droid",
            "Darth Vader", 202L,   136, "masculine",          "none",        "yellow",       "Tatooine",           "Human",
            "Leia Organa", 150L,    49,  "feminine",         "brown",         "brown",       "Alderaan",           "Human",
              "Owen Lars", 178L,   120, "masculine",   "brown, grey",          "blue",       "Tatooine",           "Human",
     "Beru Whitesun lars", 165L,    75,  "feminine",         "brown",          "blue",       "Tatooine",           "Human",
                  "R5-D4",  97L,    32, "masculine",              NA,           "red",       "Tatooine",           "Droid",
      "Biggs Darklighter", 183L,    84, "masculine",         "black",         "brown",       "Tatooine",           "Human",
         "Obi-Wan Kenobi", 182L,    77, "masculine", "auburn, white",     "blue-gray",        "Stewjon",           "Human",
       "Anakin Skywalker", 188L,    84, "masculine",         "blond",          "blue",       "Tatooine",           "Human",
         "Wilhuff Tarkin", 180L,    NA, "masculine",  "auburn, grey",          "blue",         "Eriadu",           "Human",
              "Chewbacca", 228L,   112, "masculine",         "brown",          "blue",       "Kashyyyk",         "Wookiee",
               "Han Solo", 180L,    80, "masculine",         "brown",         "brown",       "Corellia",           "Human",
                 "Greedo", 173L,    74, "masculine",              NA,         "black",          "Rodia",          "Rodian",
  "Jabba Desilijic Tiure", 175L,  1358, "masculine",              NA,        "orange",      "Nal Hutta",            "Hutt",
         "Wedge Antilles", 170L,    77, "masculine",         "brown",         "hazel",       "Corellia",           "Human",
       "Jek Tono Porkins", 180L,   110, "masculine",         "brown",          "blue",     "Bestine IV",           "Human",
                   "Yoda",  66L,    17, "masculine",         "white",         "brown",               NA,  "Yoda's species",
              "Palpatine", 170L,    75, "masculine",          "grey",        "yellow",          "Naboo",           "Human",
              "Boba Fett", 183L,  78.2, "masculine",         "black",         "brown",         "Kamino",           "Human",
                  "IG-88", 200L,   140, "masculine",          "none",           "red",               NA,           "Droid",
                  "Bossk", 190L,   113, "masculine",          "none",           "red",      "Trandosha",      "Trandoshan",
       "Lando Calrissian", 177L,    79, "masculine",         "black",         "brown",        "Socorro",           "Human",
                  "Lobot", 175L,    79, "masculine",          "none",          "blue",         "Bespin",           "Human",
                 "Ackbar", 180L,    83, "masculine",          "none",        "orange",       "Mon Cala",    "Mon Calamari",
             "Mon Mothma", 150L,    NA,  "feminine",        "auburn",          "blue",      "Chandrila",           "Human",
           "Arvel Crynyd",   NA,    NA, "masculine",         "brown",         "brown",               NA,           "Human",
  "Wicket Systri Warrick",  88L,    20, "masculine",         "brown",         "brown",          "Endor",            "Ewok",
              "Nien Nunb", 160L,    68, "masculine",          "none",         "black",        "Sullust",       "Sullustan",
           "Qui-Gon Jinn", 193L,    89, "masculine",         "brown",          "blue",               NA,           "Human",
            "Nute Gunray", 191L,    90, "masculine",          "none",           "red", "Cato Neimoidia",       "Neimodian",
          "Finis Valorum", 170L,    NA, "masculine",         "blond",          "blue",      "Coruscant",           "Human",
          "Jar Jar Binks", 196L,    66, "masculine",          "none",        "orange",          "Naboo",          "Gungan",
           "Roos Tarpals", 224L,    82, "masculine",          "none",        "orange",          "Naboo",          "Gungan",
             "Rugor Nass", 206L,    NA, "masculine",          "none",        "orange",          "Naboo",          "Gungan",
               "Ric Olié", 183L,    NA,          NA,         "brown",          "blue",          "Naboo",                NA,
                  "Watto", 137L,    NA, "masculine",         "black",        "yellow",       "Toydaria",       "Toydarian",
                "Sebulba", 112L,    40, "masculine",          "none",        "orange",      "Malastare",             "Dug",
          "Quarsh Panaka", 183L,    NA,          NA,         "black",         "brown",          "Naboo",                NA,
         "Shmi Skywalker", 163L,    NA,  "feminine",         "black",         "brown",       "Tatooine",           "Human",
             "Darth Maul", 175L,    80, "masculine",          "none",        "yellow",       "Dathomir",          "Zabrak",
            "Bib Fortuna", 180L,    NA, "masculine",          "none",          "pink",         "Ryloth",         "Twi'lek",
            "Ayla Secura", 178L,    55,  "feminine",          "none",         "hazel",         "Ryloth",         "Twi'lek",
               "Dud Bolt",  94L,    45, "masculine",          "none",        "yellow",        "Vulpter",      "Vulptereen",
                "Gasgano", 122L,    NA, "masculine",          "none",         "black",        "Troiken",           "Xexto",
         "Ben Quadinaros", 163L,    65, "masculine",          "none",        "orange",           "Tund",           "Toong",
             "Mace Windu", 188L,    84, "masculine",          "none",         "brown",     "Haruun Kal",           "Human",
           "Ki-Adi-Mundi", 198L,    82, "masculine",         "white",        "yellow",          "Cerea",          "Cerean",
              "Kit Fisto", 196L,    87, "masculine",          "none",         "black",    "Glee Anselm",        "Nautolan",
              "Eeth Koth", 171L,    NA, "masculine",         "black",         "brown",       "Iridonia",          "Zabrak",
             "Adi Gallia", 184L,    50,  "feminine",          "none",          "blue",      "Coruscant",      "Tholothian",
            "Saesee Tiin", 188L,    NA, "masculine",          "none",        "orange",        "Iktotch",        "Iktotchi",
            "Yarael Poof", 264L,    NA, "masculine",          "none",        "yellow",        "Quermia",        "Quermian",
               "Plo Koon", 188L,    80, "masculine",          "none",         "black",          "Dorin",         "Kel Dor",
             "Mas Amedda", 196L,    NA, "masculine",          "none",          "blue",       "Champala",        "Chagrian",
           "Gregar Typho", 185L,    85, "masculine",         "black",         "brown",          "Naboo",           "Human",
                  "Cordé", 157L,    NA,  "feminine",         "brown",         "brown",          "Naboo",           "Human",
            "Cliegg Lars", 183L,    NA, "masculine",         "brown",          "blue",       "Tatooine",           "Human",
      "Poggle the Lesser", 183L,    80, "masculine",          "none",        "yellow",       "Geonosis",       "Geonosian",
        "Luminara Unduli", 170L,  56.2,  "feminine",         "black",          "blue",         "Mirial",        "Mirialan",
          "Barriss Offee", 166L,    50,  "feminine",         "black",          "blue",         "Mirial",        "Mirialan",
                  "Dormé", 165L,    NA,  "feminine",         "brown",         "brown",          "Naboo",           "Human",
                  "Dooku", 193L,    80, "masculine",         "white",         "brown",        "Serenno",           "Human",
    "Bail Prestor Organa", 191L,    NA, "masculine",         "black",         "brown",       "Alderaan",           "Human",
             "Jango Fett", 183L,    79, "masculine",         "black",         "brown",   "Concord Dawn",           "Human",
             "Zam Wesell", 168L,    55,  "feminine",        "blonde",        "yellow",          "Zolan",        "Clawdite",
        "Dexter Jettster", 198L,   102, "masculine",          "none",        "yellow",           "Ojom",        "Besalisk",
                "Lama Su", 229L,    88, "masculine",          "none",         "black",         "Kamino",        "Kaminoan",
                "Taun We", 213L,    NA,  "feminine",          "none",         "black",         "Kamino",        "Kaminoan",
             "Jocasta Nu", 167L,    NA,  "feminine",         "white",          "blue",      "Coruscant",           "Human",
          "Ratts Tyerell",  79L,    15, "masculine",          "none",       "unknown",    "Aleen Minor",          "Aleena",
                 "R4-P17",  96L,    NA,  "feminine",          "none",     "red, blue",               NA,           "Droid",
             "Wat Tambor", 193L,    48, "masculine",          "none",       "unknown",          "Skako",         "Skakoan",
               "San Hill", 191L,    NA, "masculine",          "none",          "gold",     "Muunilinst",            "Muun",
               "Shaak Ti", 178L,    57,  "feminine",          "none",         "black",          "Shili",         "Togruta",
               "Grievous", 216L,   159, "masculine",          "none", "green, yellow",          "Kalee",         "Kaleesh",
                "Tarfful", 234L,   136, "masculine",         "brown",          "blue",       "Kashyyyk",         "Wookiee",
        "Raymus Antilles", 188L,    79, "masculine",         "brown",         "brown",       "Alderaan",           "Human",
              "Sly Moore", 178L,    48,          NA,          "none",         "white",         "Umbara",                NA,
             "Tion Medon", 206L,    80, "masculine",          "none",         "black",         "Utapau",          "Pau'an",
                   "Finn",   NA,    NA, "masculine",         "black",          "dark",               NA,           "Human",
                    "Rey",   NA,    NA,  "feminine",         "brown",         "hazel",               NA,           "Human",
            "Poe Dameron",   NA,    NA, "masculine",         "brown",         "brown",               NA,           "Human",
                    "BB8",   NA,    NA, "masculine",          "none",         "black",               NA,           "Droid",
         "Captain Phasma",   NA,    NA,          NA,       "unknown",       "unknown",               NA,                NA,
          "Padmé Amidala", 165L,    45,  "feminine",         "brown",         "brown",          "Naboo",           "Human"
  )
usethis::use_data(sw_summary, overwrite = TRUE)
