---
output: md_document
---

+-------------------+--------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Aesthetic         | Value                                            | Description                                                                                                                                                                                                                    |
+===================+==================================================+================================================================================================================================================================================================================================+
| `color` or `fill` | `"red"` or `"#RRGGBB"`                           | The `color` and `fill` can be set to a variable or to a value. Values are provided as a string (in quotes). See the [color section of the `ggplot2` book](https://ggplot2-book.org/scale-colour.html?q=color#scale-colour).    |
+-------------------+--------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `linetype`        | `integer` or `"string"`                          | In `geom` functions with lines, we can adjust the type of line using `linetype`.                                                                                                                                               |
|                   |                                                  |                                                                                                                                                                                                                                |
|                   |                                                  | `0` = `"blank"`                                                                                                                                                                                                                |
|                   |                                                  |                                                                                                                                                                                                                                |
|                   |                                                  | `1` = `"solid"`                                                                                                                                                                                                                |
|                   |                                                  |                                                                                                                                                                                                                                |
|                   |                                                  | `2` = `"dashed"`                                                                                                                                                                                                               |
|                   |                                                  |                                                                                                                                                                                                                                |
|                   |                                                  | `3` = `"dotted"`                                                                                                                                                                                                               |
|                   |                                                  |                                                                                                                                                                                                                                |
|                   |                                                  | `4` = `"dotdash"`                                                                                                                                                                                                              |
|                   |                                                  |                                                                                                                                                                                                                                |
|                   |                                                  | `5` = `"longdash"`                                                                                                                                                                                                             |
|                   |                                                  |                                                                                                                                                                                                                                |
|                   |                                                  | `6` = `"twodash"`                                                                                                                                                                                                              |
|                   |                                                  |                                                                                                                                                                                                                                |
|                   |                                                  | Read more about `linetype` in the [`ggplot2` text](https://ggplot2-book.org/scale-other.html?q=linet#scale-linetype)                                                                                                           |
+-------------------+--------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `lineend`         | `"round"`, `"butt"`, or `"square"`               | These aesthetics control the shape of the lines endings                                                                                                                                                                        |
+-------------------+--------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `linejoin`        | `"round"`, `"mitre"`, or `"bevel"`               | When lines are used to join observations together, we can specify how the joining line should look. Read more in the [ggplot2 book](https://ggplot2.tidyverse.org/articles/ggplot2-specs.html?q=colour#line-endjoin-paramters) |
+-------------------+--------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `size`            | integer (line width in mm)                       | `size` can be set with an integer value (or as a continuous variable).                                                                                                                                                         |
+-------------------+--------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `shape`           | integer/shape name or a single character (`"a"`) | `0`-`25` are the acceptable integers.                                                                                                                                                                                          |
+-------------------+--------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Common aesthetic values.
